### ISSUE TITLE
Add support for logging in with e-mail address OR username

### ISSUE THREAD

**Issue by SlvrEagle23** [FurryDigital/FurryDigital#20]

**Comment by IngwiePhoenix** [comment]
https://github.com/FurryDigital/FurryDigital/blob/master/app/modules/account/controllers/LoginController.php#L26

Probably want a custom auth plugin. Assuming that `BaseController` utilizes DI with `$this->auth` being an authentication plugin, such custom plugin might be required to enable this. But then again, this should be fairly simple.

**Comment by SlvrEagle23** [comment]
That actually just calls the static "authenticate" function on the `User` class, so it's rather trivial to enable e-mail based login...just need to update the query it uses.
